---
sonarr:
  api_key: "your-sonarr-api-key"
radarr:
  api_key: "your-radarr-api-key"
prowlarr:
  api_key: "your-prowlarr-api-key"
jellyfin:
  api_key: "your-jellyfin-api-key"

arr_admin:
  username: "your-admin-account-username"
  admin_password: "your-admin-password"
