---
sonarr:
  admin_password: "your-admin-password"
  api_key: "your-sonarr-api-key"
radarr:
  admin_password: "your-admin-password"
  api_key: "your-radarr-api-key"
prowlarr:
  admin_password: "your-admin-password"
  api_key: "your-prowlarr-api-key"
jellyfin:
  admin_password: "your-admin-password"
  api_key: "your-jellyfin-api-key"