---
classes:
  - arr-secrets

parameters:
  kapitan:
    compile:
      - input_type: jinja2
        input_paths:
          - templates/arr-secrets.xml.j2
        output_path: secrets/
        output_type: plain
