###############################################
# Common Keys for all apps
###############################################

x-common-keys: &common-keys
    restart: unless-stopped
    logging:
      driver: json-file
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Denver
    dns:
      - 1.1.1.1
      - 1.0.0.1

services:
###############################################
# RADARR - Movies
###############################################
  radarr:
    <<: *common-keys
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    ports:
      - 7878:7878
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/arr-stack/config/radarr:/config
      - /mnt/e/arr-stack:/data

###############################################
# SONARR - TV Shows
###############################################

  sonarr:
    <<: *common-keys
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:latest
    ports:
      - 8989:8989
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/arr-stack/config/sonarr:/config
      - /mnt/e/arr-stack:/data

###############################################
# LIDARR - Music
###############################################

  lidarr:
    <<: *common-keys
    container_name: lidarr
    image: ghcr.io/hotio/lidarr:latest
    ports:
      - 8686:8686
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/arr-stack/config/lidarr:/config
      - /mnt/e/arr-stack:/data

###############################################
# BAZARR - Subtitles
###############################################

  bazarr:
    <<: *common-keys
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:latest
    ports:
      - 6767:6767
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/arr-stack/config/bazarr:/config
      - /mnt/e/arr-stack/media:/data/media

###############################################
# PROWLARR - Indexer Manager
###############################################

  prowlarr:
    <<: *common-keys
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr:latest
    ports:
      - 9696:9696
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/arr-stack/config/prowlarr:/config

###############################################
# FLARESOLVERR - Cloudflare Bypass
###############################################

  flaresolverr:
    <<: *common-keys
    container_name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    ports:
      - 8191:8191
    environment:
      - LOG_LEVEL=info

###############################################
# QBITTORRENT - Downloader
###############################################

  qbittorrent:
    <<: *common-keys
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent:latest
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    environment:
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/arr-stack/config/qbittorrent:/config
      - /mnt/e/arr-stack:/data

###############################################
# NZBGet - Downloader
###############################################

  nxbget:
    <<: *common-keys
    container_name: nzbget
    image: ghcr.io/nzbgetcom/nzbget:latest
    ports:
      - 6789:6789
    volumes:
      - ~/arr-stack/config/nzbget:/config
      - /mnt/e/arr-stack:/data

###############################################
# JELLYFIN - Media Server
###############################################

  jellyfin:
    <<: *common-keys
    container_name: jellyfin
    image: ghcr.io/hotio/jellyfin:latest
    entrypoint: ["/bin/sh", "/config-init/init.sh"]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./jellyfin/init.sh:/config-init/init.sh:ro
      - ~/arr-stack/config/jellyfin:/config
      - /mnt/e/arr-stack/media:/data/media:ro #read-only
    ports:
      - 8096:8096

###############################################
# ARR Stack Dedicated Network
###############################################

networks:
  default:
    name: arr_network

###############################################
###############################################
